en:
  regressor__alpha:
  - 1.0
  regressor__l1_ratio:
  - 0.9
  regressor__max_iter:
  - 1000
plr:
  poli__degree:
  - 2
rfr:
  regressor__max_depth:
  - 13
  regressor__max_features:
  - 6
  regressor__min_samples_leaf:
  - 3
  regressor__n_estimators:
  - 200
svr:
  regressor__C:
  - 2
  regressor__epsilon:
  - 0.3
  regressor__kernel:
  - rbf
